### ISSUE TITLE
Very Useful/Precise - A little awkward in my case (Feature Request)

### ISSUE THREAD

**Issue by Ken98045** [HypsyNZ/Precision-Timer.NET#1]
In my case I just  need a one shot timer that would ideally just return after an accurate time.
That is - an action very similar to just Sleep(delay) or Sleep(delay, precision), but actually like ... accurate (Microsoft!).
I can code around it, but things are a little odd for the one shot case - it seems to self dispose?  However, if I don't dispose it, things also seem to break randomly after repeated calls.  Maybe when the object just goes out of scope?  It seems to work best if I just keep the default periodic repeat and then Dispose it.

Thanks for your work on this!  It is amazing that something like this isn't baked into Windows!

**Comment by HypsyNZ** [comment]
Yeah, I'm not a huge fan of `Task.Delay` or using `Thread.Sleep` and have thought about making something like this before.

I may do it, but it would be in a different project.

I prefer to keep things simple.

**Comment by HypsyNZ** [comment]
> In my case I just need a one shot timer that would ideally just return after an accurate time, but actually like ... accurate (Microsoft!).

This delay you are hinting at is caused by the drift in the `Timer` that everything in the CLR uses, Its 12-15ms depending on your hardware and is the reason this `PrecisionTimer` was created in the first place.

**Comment by HypsyNZ** [comment]
>I can code around it, but things are a little odd for the one shot case

When a one-shot fires the underlying timer stops, They really are one shot at the moment and were a bit of an afterthought, I will have another look at this soon.

Do you have any overrides for garbage collection?

**Comment by HypsyNZ** [comment]
https://github.com/HypsyNZ/Precision-Timer.NET/blob/422620060c950dc6cd35625a1f9ac8d2a59febc6/Example/Program.cs#L72

I am trying to replicate your issue but everything seems fine.

To be clear, if you call dispose the timer is destroyed.

For one shot the best method is to call `Stop` -> `Start`

**Comment by HypsyNZ** [comment]
```
One Shot Test With Varying Delay
Timer Started
Timer Ticked
Timer Stopped
One Shot will be fired after: 5000ms - 1/100
Timer Started
Timer Ticked
Timer Stopped
One Shot will be fired after: 10000ms - 2/100
Timer Started
Timer Ticked
Timer Stopped
One Shot will be fired after: 20000ms - 3/100
Timer Started
Timer Ticked
Timer Stopped
One Shot will be fired after: 40000ms - 4/100
Timer Started
Timer Ticked
Timer Stopped
One Shot will be fired after: 80000ms - 5/100
Timer Started
Timer Ticked
Timer Stopped
One Shot will be fired after: 160000ms - 6/100
Timer Started
Timer Ticked
Timer Stopped
One Shot will be fired after: 320000ms - 7/100
Timer Started
Timer Ticked
Timer Stopped
One Shot will be fired after: 640000ms - 8/100
```

... :))))

**Comment by HypsyNZ** [comment]
You can now call `Start` again without duplicating events, so you can make use of it now for `One Shot` events

You don't need to call `Stop` first anymore either.

If you have another issue and you know how to replicate it submit a [Pull Request Here](https://github.com/HypsyNZ/Precision-Timer.NET/blob/issue-replication/Example/Program.cs) or describe it in more detail.

You should not dispose these timers until you are completely done with them because of the garbage collector changes they will be destroyed at the first opportunity.

**Comment by HypsyNZ** [comment]
[![Nuget](https://img.shields.io/nuget/v/PrecisionTimer.NET)](https://www.nuget.org/packages/PrecisionTimer.NET/) Please update to the most recent release.

You can now call `Start` again without duplicating events, so you can make use of it now for `One Shot` events

You don't need to call `Stop` first anymore either for one-shot mode.

If you have another issue and you know how to replicate it submit a [Pull Request Here](https://github.com/HypsyNZ/Precision-Timer.NET/blob/issue-replication/Example/Program.cs) or describe it in more detail.

You should not dispose these timers until you are completely done with them because of the garbage collector changes they will be destroyed at the first opportunity.

You can also use `SetPeriodic(false)` to change a periodic timer into a one-shot timer without creating a new one.

**Comment by Ken98045** [comment]
Thanks for your help!

 

If you are interested here is what I’m using it for.  Many IP cameras have a limited pan/tilt/zoom.  You can start it, but then you have to stop it too.  The more accurate the timer between the actions the more accurate/repeatable the PTZ is.

**Comment by HypsyNZ** [comment]
> If you are interested here is what I’m using it for. Many IP cameras have a limited pan/tilt/zoom. You can start it, but then you have to stop it too. The more accurate the timer between the actions the more accurate/repeatable the PTZ is.

Well the default periodic timer has a `Tick` event that triggers every `1ms` you can subscribe to it like this, This is in addition to the `Action` that you can provide in `SetInterval(Action, Interval);` which is optional.

https://github.com/HypsyNZ/Precision-Timer.NET/blob/bddb1c4c695919928041bad4e5c0b9e1e839aee8/Example/Program.cs#L39

https://github.com/HypsyNZ/Precision-Timer.NET/blob/bddb1c4c695919928041bad4e5c0b9e1e839aee8/Example/Program.cs#L185-L188

This event should occur roughly 1000 times a second with no delays/sleeps added and you can start/stop it whenever you want

**Comment by Ken98045** [comment]
Here is what I came up with.  Again, the idea is to do a single high precision wait.  Please let me know if you would have done things differently.

 

  public static  int Wait(Stopwatch watch, int delay, CancellationTokenSource cancelSource)

     {

           Stopwatch watch = Stopwatch.StartNew();

     AutoResetEvent evt = new(false);

    PrecisionTimer timer = new();

    timer.SetResolution(1);

     timer.SetPeriodic(false);

    timer.SetAction(() => evt.Set());

    timer.SetInterval(delay);

    timer.SetPeriodic(false);

    timer.Start();

    evt.WaitOne(5 * delay); // Keep the timer from going out of scope (but it should probably throw if the wait times out….)

    result = (int) watch.ElapsedMilliseconds;

    return result;

}

**Comment by HypsyNZ** [comment]
```cs
PrecisionTimer timer = new();
```

I would remove the timer creation from the method and make it `static` and then call `Stop` there instead.

The timer should be pinned now it shouldn't dispose until you close the application or call dispose, I changed the garbage collection based on your feedback, let me know if it still disappears randomly when using `one-shot`

**Comment by HypsyNZ** [comment]
It seems like [Timer-Sink.NET`](https://github.com/HypsyNZ/Timer-Sink.NET) might be better suited for what you are trying to do

**Comment by Ken98045** [comment]
Actually, not.  Because I sometimes need sub-10ms delays.  Anything with any kind of tasks involves a context switch that can take a minimum 10ms and/or is somewhat coarse.  If I were always dealing with plus 10ms I’d have a wealth of options.   That said, I haven’t actually tried the Timer-Sink project.

 

Yours is the best option I’ve found.
