### ISSUE TITLE
After a few seconds of running an error is thrown

### ISSUE THREAD

**Issue by rradnet** [HypsyNZ/Precision-Timer.NET#3]
The event can't be missing because it runs correctly through the event for a few seconds. And then:
PrecisionTiming.TimerTaskFailed: [Callback] Timer Task Failed - Tick EventHandler was missing.
Using the latest version 2.2.4.6
Version 2.2.4.5-4 will just stop working instead of the error.
Version 2.2.4.1 seems to be stable.

**Comment by HypsyNZ** [comment]
Can you post an example of how you are creating the timer

**Comment by HypsyNZ** [comment]
> Version 2.2.4.5-4 will just stop working instead of the error.

These shouldn't have been listed, thank you.

> Version 2.2.4.1 seems to be stable. 

Yes it is very stable.

**Comment by HypsyNZ** [comment]
Can you post an example of how you are creating the timer?

Did you manually configure it at all?

What are you doing inside the `Tick` event?

Did you call `Stop` ?

**Comment by HypsyNZ** [comment]
If you can replicate your issue reliably in a simple example can you please make a [pull request](https://github.com/HypsyNZ/Precision-Timer.NET/tree/issue-replication) in this branch

**Comment by HypsyNZ** [comment]
![exception](https://user-images.githubusercontent.com/54571583/186961278-83f04d32-e054-45ef-befd-cf22fb59bdcd.png)

This exception will also throw if there is an exception in your callback method.

You'll have to debug to see the real exception, unwinding here is not wise.

**Comment by HypsyNZ** [comment]
Can you post an example of how you are creating the timer?

Did you manually configure it at all?

What are you doing inside the `Tick` event?

---------

![exception](https://user-images.githubusercontent.com/54571583/186961278-83f04d32-e054-45ef-befd-cf22fb59bdcd.png)

This exception will also throw if there is an unhandled exception in your callback method.

You'll have to debug to see the real exception, unwinding here is not wise.

**Comment by HypsyNZ** [comment]
If you can replicate your issue reliably in a simple example can you please make a [pull request](https://github.com/HypsyNZ/Precision-Timer.NET/blob/issue-replication/Example/Program.cs) in this branch

**Comment by HypsyNZ** [comment]
Can you post an example of how you are creating the timer?

Did you manually configure it at all?

What are you doing inside the `Tick` event?

Do you handle possible exceptions in your callback?

---------

![exception](https://user-images.githubusercontent.com/54571583/186961278-83f04d32-e054-45ef-befd-cf22fb59bdcd.png)

This exception will also throw if there is an unhandled exception in your callback method.

You'll have to debug to see the real exception, unwinding here is not wise.

**Comment by HypsyNZ** [comment]
`exceptionString` will be changed to `Unhandled Exception During Timer Callback - Attach debugger for more information` in a future update

**Comment by HypsyNZ** [comment]
```cs
        private static void Tick(object sender, EventArgs args)
        {
            try
            {
                // Your Code
            }
            catch
            {
                // Ignore Exceptions
            }

            Console.WriteLine("Timer Ticked");
        }
```

You can ignore whatever is causing the exception if you want but if you let it reach there it will throw.

**Comment by HypsyNZ** [comment]
![exception](https://user-images.githubusercontent.com/54571583/186961278-83f04d32-e054-45ef-befd-cf22fb59bdcd.png)

This exception will throw if there is an unhandled exception in your callback method.

----

Using the [example](https://github.com/HypsyNZ/Precision-Timer.NET/blob/main/Example/Program.cs)

```cs
        private static void Tick(object sender, EventArgs args)
        {
            try
            {
                // Your Code
            }
            catch
            {
                // Ignore Exceptions
            }

            Console.WriteLine("Timer Ticked");
        }
```

You can ignore whatever is causing the exception if you want but if you let it reach there it will throw.

If I haven't described your issue and you can replicate your issue reliably in a simple example can you please make a [pull request](https://github.com/HypsyNZ/Precision-Timer.NET/blob/issue-replication/Example/Program.cs) in this branch
